# Generated by Django 4.2.7 on 2023-11-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='User id')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Adress')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Member since')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
